In [1]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy import stats
from linearmodels.system import SUR
from scipy.stats import ttest_1samp

C:\Anaconda\lib\site-packages\linearmodels\panel\data.py:10: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  from pandas import (Categorical, DataFrame, Index, MultiIndex, Panel, Series,

In [2]:
# Dataset for Q1
df = pd.read_stata('pset2.dta')
df.describe()

,female,boston,education,ofjobs,yearsexp,yearsexp2,honors,volunteer,military,empholes,...,orgreq,manuf,transcom,bankreal,trade,busservice,othservice,missind,_est_m1,_est_m2
count,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,...,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000,4870.000000
mean,0.769199,0.444764,3.618480,3.661396,7.842916,86.954208,0.052772,0.411499,0.097125,0.448049,...,0.072690,0.082957,0.030390,0.085010,0.213963,0.267762,0.154825,0.165092,0.500000,0.500000
std,0.421398,0.496991,0.714997,1.219126,5.044612,128.309616,0.223601,0.492156,0.296159,0.497345,...,0.259649,0.275854,0.171677,0.278932,0.410141,0.442847,0.361773,0.371308,0.500051,0.500051
min,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,0.000000,3.000000,3.000000,5.000000,25.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1.000000,0.000000,4.000000,4.000000,6.000000,36.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.500000
75%,1.000000,1.000000,4.000000,4.000000,9.000000,81.000000,0.000000,1.000000,0.000000,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,1.000000,1.000000,4.000000,7.000000,44.000000,1936.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [3]:
df.head()

,id,female,race,boston,ad,education,ofjobs,yearsexp,yearsexp2,honors,...,manuf,transcom,bankreal,trade,busservice,othservice,missind,ownership,_est_m1,_est_m2
0,b,1.0,w,0,1,4,2,6,36.0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,,1,0
1,b,1.0,w,0,1,3,3,6,36.0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,,1,0
2,b,1.0,b,0,1,4,1,6,36.0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,,0,1
3,b,1.0,b,0,1,3,4,6,36.0,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,,0,1
4,b,1.0,w,0,1,3,3,22,484.0,0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,Nonprofit,1,0

In [4]:
# 1.1
# white names
df_white = df[df['race'] == 'w']
smf.probit(formula = 'call ~ yearsexp + yearsexp2 + volunteer + military + email + empholes + workinschool + honors + computerskills + specialskills + boston + female + manager + supervisor + secretary + salesrep + retailsales + offsupport + req + expreq + comreq + educreq + compreq + orgreq', data = df_white).fit(cov_type='cluster', cov_kwds={'groups': df_white['adid']}).get_margeff().summary()

Optimization terminated successfully.
         Current function value: 0.297453
         Iterations 6

C:\Anaconda\lib\site-packages\statsmodels\discrete\discrete_margins.py:343: RuntimeWarning: invalid value encountered in sqrt
  return cov_me, np.sqrt(np.diag(cov_me))
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in greater
  return (a < x) & (x < b)
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:901: RuntimeWarning: invalid value encountered in less
  return (a < x) & (x < b)
C:\Anaconda\lib\site-packages\scipy\stats\_distn_infrastructure.py:1892: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= _a)

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects
=====================================
Dep. Variable:                   call
Method:                          dydx
At:                           overall
==================================================================================
                    dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
yearsexp           0.0138        nan        nan        nan         nan         nan
yearsexp2         -0.0005        nan        nan        nan         nan         nan
volunteer         -0.0164      0.018     -0.917      0.359      -0.051       0.019
military           0.0220      0.019      1.134      0.257      -0.016       0.060
email              0.0286      0.023      1.238      0.216      -0.017       0.074
empholes           0.0326      0.014      2.271      0.023       0.004       0.061
workinschool       0.0198      0.011      1.770      0.077      -0.002       0.042
honors             0.0533      0.027      1.986      0.047       0.001       0.106
computerskills    -0.0384      0.010     -4.016      0.000      -0.057      -0.020
specialskills      0.0604      0.024      2.548      0.011       0.014       0.107
boston             0.0273      0.019      1.449      0.147      -0.010       0.064
female             0.0007      0.017      0.039      0.969      -0.033       0.034
manager           -0.0613        nan        nan        nan         nan         nan
supervisor        -0.0368        nan        nan        nan         nan         nan
secretary         -0.0270        nan        nan        nan         nan         nan
salesrep          -0.0593        nan        nan        nan         nan         nan
retailsales       -0.0493        nan        nan        nan         nan         nan
offsupport        -0.0255        nan        nan        nan         nan         nan
req               -0.0317      0.024     -1.296      0.195      -0.080       0.016
expreq             0.0104      0.017      0.602      0.547      -0.023       0.044
comreq             0.0234      0.022      1.062      0.288      -0.020       0.067
educreq           -0.0072      0.023     -0.308      0.758      -0.053       0.039
compreq           -0.0147      0.022     -0.675      0.499      -0.057       0.028
orgreq            -0.0547      0.032     -1.698      0.090      -0.118       0.008
==================================================================================
"""

In [5]:
# black names
df_black = df[df['race'] == 'b']
smf.probit(formula = 'call ~ yearsexp + yearsexp2 + volunteer + military + email + empholes + workinschool + honors + computerskills + specialskills + boston + female + manager + supervisor + secretary + salesrep + retailsales + offsupport + req + expreq + comreq + educreq + compreq + orgreq', data = df_black).fit(cov_type='cluster', cov_kwds={'groups': df_black['adid']}).get_margeff().summary()

Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.228434
         Iterations: 35

C:\Anaconda\lib\site-packages\statsmodels\base\model.py:512: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  "Check mle_retvals", ConvergenceWarning)

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects
=====================================
Dep. Variable:                   call
Method:                          dydx
At:                           overall
==================================================================================
                    dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
yearsexp           0.0021      0.004      0.570      0.568      -0.005       0.009
yearsexp2      -6.003e-06      0.000     -0.055      0.956      -0.000       0.000
volunteer          0.0066      0.015      0.439      0.660      -0.023       0.036
military          -0.0176      0.017     -1.036      0.300      -0.051       0.016
email              0.0002      0.013      0.017      0.986      -0.025       0.026
empholes           0.0137      0.016      0.855      0.393      -0.018       0.045
workinschool      -0.0012      0.012     -0.101      0.919      -0.025       0.022
honors             0.0267      0.020      1.306      0.192      -0.013       0.067
computerskills    -0.0014      0.014     -0.097      0.923      -0.029       0.027
specialskills      0.0403      0.008      5.324      0.000       0.025       0.055
boston             0.0138      0.015      0.933      0.351      -0.015       0.043
female             0.0047      0.013      0.355      0.722      -0.021       0.031
manager           -0.0432   1.47e+05  -2.94e-07      1.000   -2.88e+05    2.88e+05
supervisor        -0.0467        nan        nan        nan         nan         nan
secretary         -0.0326   2.86e+05  -1.14e-07      1.000    -5.6e+05     5.6e+05
salesrep          -0.0365   6.37e+05  -5.73e-08      1.000   -1.25e+06    1.25e+06
retailsales       -0.0231   3.07e+05  -7.54e-08      1.000   -6.01e+05    6.01e+05
offsupport        -0.0168   6.87e+05  -2.44e-08      1.000   -1.35e+06    1.35e+06
req                0.0043      0.018      0.247      0.805      -0.030       0.039
expreq             0.0058      0.016      0.357      0.721      -0.026       0.038
comreq             0.0078      0.019      0.401      0.688      -0.030       0.046
educreq           -0.0406      0.020     -2.010      0.044      -0.080      -0.001
compreq           -0.0142      0.019     -0.765      0.444      -0.051       0.022
orgreq            -0.0186      0.029     -0.638      0.523      -0.076       0.039
==================================================================================
"""

In [6]:
# all
smf.probit(formula = 'call ~ yearsexp + yearsexp2 + volunteer + military + email + empholes + workinschool + honors + computerskills + specialskills + boston + female + manager + supervisor + secretary + salesrep + retailsales + offsupport + req + expreq + comreq + educreq + compreq + orgreq', data = df).fit(cov_type='cluster', cov_kwds={'groups': df['adid']}).get_margeff().summary()

Optimization terminated successfully.
         Current function value: 0.266175
         Iterations 6

<class 'statsmodels.iolib.summary.Summary'>
"""
       Probit Marginal Effects
=====================================
Dep. Variable:                   call
Method:                          dydx
At:                           overall
==================================================================================
                    dy/dx    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
yearsexp           0.0074      0.002      3.143      0.002       0.003       0.012
yearsexp2         -0.0002      0.000     -2.029      0.042      -0.000   -7.08e-06
volunteer         -0.0062      0.011     -0.571      0.568      -0.027       0.015
military           0.0012      0.015      0.080      0.936      -0.028       0.030
email              0.0153      0.010      1.457      0.145      -0.005       0.036
empholes           0.0231      0.010      2.350      0.019       0.004       0.042
workinschool       0.0098      0.008      1.193      0.233      -0.006       0.026
honors             0.0421      0.014      2.981      0.003       0.014       0.070
computerskills    -0.0199      0.011     -1.879      0.060      -0.041       0.001
specialskills      0.0509      0.011      4.464      0.000       0.029       0.073
boston             0.0208      0.014      1.502      0.133      -0.006       0.048
female             0.0025      0.011      0.226      0.821      -0.019       0.025
manager           -0.0508   4.42e+05  -1.15e-07      1.000   -8.65e+05    8.65e+05
supervisor        -0.0429   3.44e+05  -1.25e-07      1.000   -6.74e+05    6.74e+05
secretary         -0.0309   3.29e+05  -9.38e-08      1.000   -6.45e+05    6.45e+05
salesrep          -0.0479   3.78e+05  -1.27e-07      1.000   -7.41e+05    7.41e+05
retailsales       -0.0360   2.82e+05  -1.28e-07      1.000   -5.52e+05    5.52e+05
offsupport        -0.0217   2.56e+05  -8.47e-08      1.000   -5.01e+05    5.01e+05
req               -0.0140      0.019     -0.741      0.459      -0.051       0.023
expreq             0.0088      0.014      0.621      0.534      -0.019       0.037
comreq             0.0153      0.018      0.833      0.405      -0.021       0.051
educreq           -0.0220      0.019     -1.147      0.251      -0.060       0.016
compreq           -0.0134      0.016     -0.823      0.411      -0.045       0.018
orgreq            -0.0357      0.027     -1.325      0.185      -0.088       0.017
==================================================================================
"""